### ISSUE TITLE
Proposal: Add a Slider component

### ISSUE THREAD

**Issue by ynotdraw** [lifeomic/chroma-react#200]
Chroma should provide a Slider component.  This is something @HaleyWardo and @dexterca have already (to some degree) in one of our apps.  It'd be awesome to move it over as a proper component.

**Comment by HaleyWardo** [comment]
I started moving over the slider component that we have in another app. I need to take a pause on this and move over to something else. I will try to come back and work on this but if someone wants to take over from where I left off, that would be amazing! 

Branch : `feat/slider`

Since we are overriding the native styles, we lose the styling for the progress fill and disabled. I found this [article](https://dev.to/munkacsimark/styled-range-input-a-way-out-of-range-input-nightmare-jeo) helpful in achieving the progress fill. I didn't have the chance to look into the disabled styles.
